name: GitHub Pages Astro CI

on:
  # Activa el workflow cada vez que hay un push a la rama `main`
  # ¿Estás usando un nombre diferente de rama? Reemplaza `main` con el nombre de tu rama
  push:
    branches: [dev]
  # Te permite ejecutar este workflow manualmente desde la pestaña Actions en GitHub.
  workflow_dispatch:

# Permite clonar el repositorio y desplegar el proyecto
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Install, build, and upload your site
        uses: withastro/action@v1
        with:
          package-manager:
            pnpm@latest # El gestor de paquetes de Node que debe instalar las dependencias y compilar tu proyecto. Automáticamente detectadas con base en tu archivo lockfile. (opcional)
            # path: . # La ubicación de la raíz de tu proyecto de Astro dentro del repositorio. (opcional)
            # node-version: 18.18.0 # La versión específica de Node que debe utilizarse para compilar tu proyecto. Por defecto es la 18. (opcional)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://github.com/Breimerct/to-do-list-astro-dev
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

      # Puedes agregar comandos adicionales después del despliegue si es necesario
      - name: Finish Deploy
        run: |
          echo "Deployed successfully!"
